/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParaCreatorsRouteImport } from './routes/para-creators'
import { Route as ParaEmpresasRouteImport } from './routes/para-empresas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaCreatorsRoute = ParaCreatorsRouteImport.update({
  id: '/para-creators',
  path: '/para-creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaEmpresasRoute = ParaEmpresasRouteImport.update({
  id: '/para-empresas',
  path: '/para-empresas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/para-creators': typeof ParaCreatorsRoute
  '/para-empresas': typeof ParaEmpresasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/para-creators': typeof ParaCreatorsRoute
  '/para-empresas': typeof ParaEmpresasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/para-creators': typeof ParaCreatorsRoute
  '/para-empresas': typeof ParaEmpresasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/para-creators' | '/para-empresas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/para-creators' | '/para-empresas'
  id: '__root__' | '/' | '/para-creators' | '/para-empresas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParaCreatorsRoute: typeof ParaCreatorsRoute
  ParaEmpresasRoute: typeof ParaEmpresasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-creators': {
      id: '/para-creators'
      path: '/para-creators'
      fullPath: '/para-creators'
      preLoaderRoute: typeof ParaCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-empresas': {
      id: '/para-empresas'
      path: '/para-empresas'
      fullPath: '/para-empresas'
      preLoaderRoute: typeof ParaEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParaCreatorsRoute: ParaCreatorsRoute,
  ParaEmpresasRoute: ParaEmpresasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
