/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CadastroEmpresaRouteImport } from './routes/cadastro-empresa'
import { Route as ParaCreatorsRouteImport } from './routes/para-creators'
import { Route as ParaEmpresasRouteImport } from './routes/para-empresas'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppMatchesRouteImport } from './routes/app.matches'
import { Route as AppOportunidadesRouteImport } from './routes/app.oportunidades'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppSalvosRouteImport } from './routes/app.salvos'
import { Route as AppOportunidadeIdRouteImport } from './routes/app.oportunidade.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroEmpresaRoute = CadastroEmpresaRouteImport.update({
  id: '/cadastro-empresa',
  path: '/cadastro-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaCreatorsRoute = ParaCreatorsRouteImport.update({
  id: '/para-creators',
  path: '/para-creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaEmpresasRoute = ParaEmpresasRouteImport.update({
  id: '/para-empresas',
  path: '/para-empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppOportunidadesRoute = AppOportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppSalvosRoute = AppSalvosRouteImport.update({
  id: '/salvos',
  path: '/salvos',
  getParentRoute: () => AppRoute,
} as any)
const AppOportunidadeIdRoute = AppOportunidadeIdRouteImport.update({
  id: '/oportunidade/$id',
  path: '/oportunidade/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/para-creators': typeof ParaCreatorsRoute
  '/para-empresas': typeof ParaEmpresasRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/oportunidades': typeof AppOportunidadesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/salvos': typeof AppSalvosRoute
  '/app/': typeof AppIndexRoute
  '/app/oportunidade/$id': typeof AppOportunidadeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/para-creators': typeof ParaCreatorsRoute
  '/para-empresas': typeof ParaEmpresasRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/oportunidades': typeof AppOportunidadesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/salvos': typeof AppSalvosRoute
  '/app': typeof AppIndexRoute
  '/app/oportunidade/$id': typeof AppOportunidadeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/para-creators': typeof ParaCreatorsRoute
  '/para-empresas': typeof ParaEmpresasRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/oportunidades': typeof AppOportunidadesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/salvos': typeof AppSalvosRoute
  '/app/': typeof AppIndexRoute
  '/app/oportunidade/$id': typeof AppOportunidadeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/cadastro-empresa'
    | '/para-creators'
    | '/para-empresas'
    | '/app/matches'
    | '/app/oportunidades'
    | '/app/perfil'
    | '/app/salvos'
    | '/app/'
    | '/app/oportunidade/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/cadastro-empresa'
    | '/para-creators'
    | '/para-empresas'
    | '/app/matches'
    | '/app/oportunidades'
    | '/app/perfil'
    | '/app/salvos'
    | '/app'
    | '/app/oportunidade/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/cadastro-empresa'
    | '/para-creators'
    | '/para-empresas'
    | '/app/matches'
    | '/app/oportunidades'
    | '/app/perfil'
    | '/app/salvos'
    | '/app/'
    | '/app/oportunidade/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CadastroEmpresaRoute: typeof CadastroEmpresaRoute
  ParaCreatorsRoute: typeof ParaCreatorsRoute
  ParaEmpresasRoute: typeof ParaEmpresasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-empresa': {
      id: '/cadastro-empresa'
      path: '/cadastro-empresa'
      fullPath: '/cadastro-empresa'
      preLoaderRoute: typeof CadastroEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-creators': {
      id: '/para-creators'
      path: '/para-creators'
      fullPath: '/para-creators'
      preLoaderRoute: typeof ParaCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-empresas': {
      id: '/para-empresas'
      path: '/para-empresas'
      fullPath: '/para-empresas'
      preLoaderRoute: typeof ParaEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matches': {
      id: '/app/matches'
      path: '/matches'
      fullPath: '/app/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/oportunidades': {
      id: '/app/oportunidades'
      path: '/oportunidades'
      fullPath: '/app/oportunidades'
      preLoaderRoute: typeof AppOportunidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/salvos': {
      id: '/app/salvos'
      path: '/salvos'
      fullPath: '/app/salvos'
      preLoaderRoute: typeof AppSalvosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/oportunidade/$id': {
      id: '/app/oportunidade/$id'
      path: '/oportunidade/$id'
      fullPath: '/app/oportunidade/$id'
      preLoaderRoute: typeof AppOportunidadeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMatchesRoute: typeof AppMatchesRoute
  AppOportunidadesRoute: typeof AppOportunidadesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppSalvosRoute: typeof AppSalvosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOportunidadeIdRoute: typeof AppOportunidadeIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMatchesRoute: AppMatchesRoute,
  AppOportunidadesRoute: AppOportunidadesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppSalvosRoute: AppSalvosRoute,
  AppIndexRoute: AppIndexRoute,
  AppOportunidadeIdRoute: AppOportunidadeIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CadastroEmpresaRoute: CadastroEmpresaRoute,
  ParaCreatorsRoute: ParaCreatorsRoute,
  ParaEmpresasRoute: ParaEmpresasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
